
package View;

import impressora_jasperPaci.Laboratorio2;
import Impressora_Jaspe.Tela_Cadastramento;
import Impressora_jasperexame.tela_exame;
import ModeloConection.ConexaoBd;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author gabri
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    ConexaoBd conecta = new ConexaoBd();
    Tela_Cadastramento tela = new Tela_Cadastramento();
        Laboratorio2 telalab = new Laboratorio2();
        tela_exame telaexa = new tela_exame();
        
        
    public Menu_Principal() {
        
        
        initComponents();
        conecta.Conexao();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFramebemvindo = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOperaçao = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFramebemvindo.setTitle("Bem-Vindo");
        jInternalFramebemvindo.setVisible(true);
        jInternalFramebemvindo.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Sistema Ed-Otica");
        jInternalFramebemvindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1234, 29);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-marrom-long-hair-lady-com-óculos-vermelhos-50.png"))); // NOI18N
        jButton1.setText("Cadastro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFramebemvindo.getContentPane().add(jButton1);
        jButton1.setBounds(10, 160, 150, 170);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1 (2).png"))); // NOI18N
        jButton2.setText("Laboratorio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFramebemvindo.getContentPane().add(jButton2);
        jButton2.setBounds(170, 160, 150, 170);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1 (1).png"))); // NOI18N
        jButton3.setText("Exame");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jInternalFramebemvindo.getContentPane().add(jButton3);
        jButton3.setBounds(330, 160, 150, 170);

        jLabel6.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        jLabel6.setText("Relatorios-");
        jInternalFramebemvindo.getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 140, 130, 19);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo-menu.png"))); // NOI18N
        jInternalFramebemvindo.getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 1180, 570);

        jDesktopPane1.add(jInternalFramebemvindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 1180, 610));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Desenvolvido por Gsistemas");
        jDesktopPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 300, -1));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -30, 1570, 920));

        jMenuOperaçao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/medical-report.png"))); // NOI18N
        jMenuOperaçao.setText("Relatorios");
        jMenuOperaçao.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-marrom-long-hair-lady-com-óculos-vermelhos-50.png"))); // NOI18N
        jMenuItem1.setText("Cadastro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuOperaçao.add(jMenuItem1);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1 (2).png"))); // NOI18N
        jMenuItem4.setText("Laboratorio");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuOperaçao.add(jMenuItem4);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1 (1).png"))); // NOI18N
        jMenuItem3.setText("Exame");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuOperaçao.add(jMenuItem3);

        jMenuBar1.add(jMenuOperaçao);

        jMenuSair.setText("Sair");
        jMenuSair.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-sair-48.png"))); // NOI18N
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItem2);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1378, 815));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Açao butao
        
       // Tela_Cadastramento tela = new Tela_Cadastramento();
        //tela.setVisible(true);
        if (tela == null){
            tela = new Tela_Cadastramento();
            tela.setVisible(true);
            tela.setResizable(false);
        }else{
        tela.setVisible(true);
        tela.setResizable(false);
    }
       
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        conecta.Desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        //Laboratorio lab = new Laboratorio ();
        //lab.setVisible(true);
        
        if (telalab==null){
            telalab = new Laboratorio2();
            telalab.setVisible(true);
            telalab.setResizable(false);
            
        }else 
            telalab.setVisible(true);
            telalab.setResizable(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        //tela_exame ex = new tela_exame();
       // ex.setVisible(true);
        
       if (telaexa==null){
            telaexa = new tela_exame();
           telaexa.setVisible(true);
            telaexa.setResizable(false);
            
        }else 
            telaexa.setVisible(true);
            telaexa.setResizable(false);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (tela == null){
            tela = new Tela_Cadastramento();
            tela.setVisible(true);
            tela.setResizable(false);
        }else{
        tela.setVisible(true);
        tela.setResizable(false);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if (telalab==null){
            telalab = new Laboratorio2();
            telalab.setVisible(true);
            telalab.setResizable(false);
            
        }else 
            telalab.setVisible(true);
            telalab.setResizable(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (telaexa==null){
            telaexa = new tela_exame();
           telaexa.setVisible(true);
            telaexa.setResizable(false);
            
        }else 
            telaexa.setVisible(true);
            telaexa.setResizable(false);
    }//GEN-LAST:event_jButton3ActionPerformed
      
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFramebemvindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jMenuOperaçao;
    private javax.swing.JMenu jMenuSair;
    // End of variables declaration//GEN-END:variables

    
    
}
