/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package impressora_jasperPaci;
import ModeloBeans.BenasPacientes;
import ModeloBeans.ModeloTab;
import ModeloConection.ConexaoBd;
import ModeloDao.DaoPcientes;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;


public class Laboratorio2 extends javax.swing.JFrame {

     ConexaoBd conex = new ConexaoBd();
    BenasPacientes pac = new BenasPacientes();
    
    DaoPcientes dao = new DaoPcientes();
    int flag=0; 
    int resposta=0;
    public Laboratorio2() {
        initComponents();
        preencherPaciente();
        // manutençao feita
        PreencherTabela("select paci_codigo ,paci_dataemissao,nome_cliente,paci_fone,paci_tipodearmaçao,paci_marca,paci_ref,paci_cor,paci_valor,paci_pconta,paci_resta,paci_obs,paci_prometidopara,paci_formadepat,paci_odesflonge,paci_odcillonge,paci_odeixolonge,paci_oeesflonge,paci_oecillonge,paci_oeeixolonge,paci_odesfperto,paci_odcilperto,paci_odeixoperto,paci_oeesfperto,paci_oecilperto,paci_oeeixoperto,paci_dp,paci_alt,paci_tipodelente from pacientes inner join clientes2 on paci_codigo=cod_cliente order by cod_cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextarma = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBoxcliente = new javax.swing.JComboBox<String>();
        jSeparatorBORDAS = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabelLONGE = new javax.swing.JLabel();
        jLabeLESF = new javax.swing.JLabel();
        jLabelCIL = new javax.swing.JLabel();
        jLabelEIXO = new javax.swing.JLabel();
        jTextodesflonge = new javax.swing.JTextField();
        jLabelOD = new javax.swing.JLabel();
        jLabelOE = new javax.swing.JLabel();
        jLabelPERTO = new javax.swing.JLabel();
        jLabelOD2 = new javax.swing.JLabel();
        jLabelOE2 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabelDP = new javax.swing.JLabel();
        jLabelALT = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabelTIPOLENTE = new javax.swing.JLabel();
        jTextodcillonge = new javax.swing.JTextField();
        jTextodeixolonge = new javax.swing.JTextField();
        jTextoeesflonge = new javax.swing.JTextField();
        jTextcod = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextoecillonge = new javax.swing.JTextField();
        jTextoeeixolonge = new javax.swing.JTextField();
        jTextodesfperto = new javax.swing.JTextField();
        jTextodcilperto = new javax.swing.JTextField();
        jTextodeixoperto = new javax.swing.JTextField();
        jTextoeesfperto = new javax.swing.JTextField();
        jTextoecilperto = new javax.swing.JTextField();
        jTextoeeixoperto = new javax.swing.JTextField();
        jTextdp = new javax.swing.JTextField();
        jTextalt = new javax.swing.JTextField();
        jTexttipodelente = new javax.swing.JTextField();
        jFormattedDATAE = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextmarca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextref = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextcor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextvalor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextconta = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextresta = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextforma = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jFormattedprometido = new javax.swing.JFormattedTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jTextbuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePaciente = new javax.swing.JTable();
        jButtonnovo = new javax.swing.JButton();
        jButtonfinalizar = new javax.swing.JButton();
        jButtonalterar = new javax.swing.JButton();
        jButtonexcluir = new javax.swing.JButton();
        jButtonimprimir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jCombofone = new javax.swing.JComboBox<String>();
        textobs = new java.awt.TextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laboratorio");

        jLabel4.setText("AV: Salvador Teixeira, Nº 192");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ED ÓTICA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 20));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Data Da Emissao:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cliente:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, 30));

        jLabel11.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tipo de Armaçao");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jTextarma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextarma.setEnabled(false);
        jPanel1.add(jTextarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 250, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 1130, -1));

        jComboBoxcliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxcliente.setEnabled(false);
        jComboBoxcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxclienteActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 270, 30));

        jSeparatorBORDAS.setBackground(new java.awt.Color(0, 0, 0));
        jSeparatorBORDAS.setForeground(new java.awt.Color(0, 0, 0));
        jSeparatorBORDAS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparatorBORDAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 340, 370));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("A ESPECIALISTA DA SUA VISAO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 280, -1));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 340, -1));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 340, 10));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 340, 10));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 340, -1));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 340, 10));

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 250, 280));

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 160, 320));

        jSeparator14.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 10, 280));

        jLabelLONGE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLONGE.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLONGE.setText("LONGE");
        jPanel1.add(jLabelLONGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 70, 40));

        jLabeLESF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeLESF.setForeground(new java.awt.Color(255, 255, 255));
        jLabeLESF.setText("ESF.");
        jPanel1.add(jLabeLESF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 60, 30));

        jLabelCIL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCIL.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCIL.setText("CIL");
        jPanel1.add(jLabelCIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 60, 30));

        jLabelEIXO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEIXO.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEIXO.setText("EIXO");
        jPanel1.add(jLabelEIXO, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 40, 30));

        jTextodesflonge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextodesflonge.setEnabled(false);
        jPanel1.add(jTextodesflonge, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 90, 50));

        jLabelOD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelOD.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOD.setText("OD");
        jPanel1.add(jLabelOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 60, 30));

        jLabelOE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelOE.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOE.setText("OE");
        jPanel1.add(jLabelOE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 60, -1));

        jLabelPERTO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPERTO.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPERTO.setText("PERTO");
        jPanel1.add(jLabelPERTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabelOD2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelOD2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOD2.setText("OD");
        jPanel1.add(jLabelOD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 50, -1));

        jLabelOE2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelOE2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOE2.setText("OE");
        jPanel1.add(jLabelOE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 40, -1));

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator15.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 340, 10));

        jLabelDP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDP.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDP.setText("DP");
        jPanel1.add(jLabelDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 20, -1));

        jLabelALT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelALT.setForeground(new java.awt.Color(255, 255, 255));
        jLabelALT.setText("ALT");
        jPanel1.add(jLabelALT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 600, -1, -1));

        jSeparator16.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 340, 10));

        jLabelTIPOLENTE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTIPOLENTE.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTIPOLENTE.setText("TIPO DE LENTE ");
        jPanel1.add(jLabelTIPOLENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, -1, -1));

        jTextodcillonge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextodcillonge.setEnabled(false);
        jPanel1.add(jTextodcillonge, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 352, 90, 50));

        jTextodeixolonge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextodeixolonge.setEnabled(false);
        jPanel1.add(jTextodeixolonge, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 352, 80, 50));

        jTextoeesflonge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextoeesflonge.setEnabled(false);
        jPanel1.add(jTextoeesflonge, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 402, 90, 50));

        jTextcod.setEnabled(false);
        jPanel1.add(jTextcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 60, -1));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nº");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, 30));

        jTextoecillonge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextoecillonge.setEnabled(false);
        jPanel1.add(jTextoecillonge, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 402, 90, 50));

        jTextoeeixolonge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextoeeixolonge.setEnabled(false);
        jPanel1.add(jTextoeeixolonge, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 402, 80, 50));

        jTextodesfperto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextodesfperto.setEnabled(false);
        jPanel1.add(jTextodesfperto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 502, 90, 50));

        jTextodcilperto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextodcilperto.setEnabled(false);
        jPanel1.add(jTextodcilperto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 502, 90, 50));

        jTextodeixoperto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextodeixoperto.setEnabled(false);
        jPanel1.add(jTextodeixoperto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 502, 80, 50));

        jTextoeesfperto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextoeesfperto.setEnabled(false);
        jPanel1.add(jTextoeesfperto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 552, 90, 40));

        jTextoecilperto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextoecilperto.setEnabled(false);
        jPanel1.add(jTextoecilperto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 552, 90, 40));

        jTextoeeixoperto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextoeeixoperto.setEnabled(false);
        jPanel1.add(jTextoeeixoperto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 552, 80, 40));

        jTextdp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextdp.setEnabled(false);
        jPanel1.add(jTextdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 592, 140, 40));

        jTextalt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextalt.setEnabled(false);
        jPanel1.add(jTextalt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 592, 130, 40));

        jTexttipodelente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTexttipodelente.setEnabled(false);
        jPanel1.add(jTexttipodelente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 632, 240, 50));

        try {
            jFormattedDATAE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedDATAE.setEnabled(false);
        jFormattedDATAE.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jFormattedDATAE, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 130, 30));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Marca:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 60, 30));

        jTextmarca.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextmarca.setEnabled(false);
        jPanel1.add(jTextmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 210, 30));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("REF.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 60, 30));

        jTextref.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextref.setEnabled(false);
        jPanel1.add(jTextref, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 100, 30));

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("COR:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 60, 30));

        jTextcor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextcor.setEnabled(false);
        jPanel1.add(jTextcor, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 120, 30));

        jLabel13.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Valor R$:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        jTextvalor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextvalor.setEnabled(false);
        jPanel1.add(jTextvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 130, -1));

        jLabel14.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("P/Conta R$:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        jTextconta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextconta.setEnabled(false);
        jPanel1.add(jTextconta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 110, -1));

        jLabel15.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Resta R$;");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 80, -1));

        jTextresta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextresta.setEnabled(false);
        jPanel1.add(jTextresta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 110, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Obs.");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Forma de Patº.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        jTextforma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextforma.setEnabled(false);
        jPanel1.add(jTextforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 220, 30));

        jLabel17.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Prometido Para:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, -1, -1));

        try {
            jFormattedprometido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedprometido.setEnabled(false);
        jFormattedprometido.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jFormattedprometido, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 220, 30));

        jDesktopPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextbuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jDesktopPane2.add(jTextbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 170, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, -1, 30));

        jTablePaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePaciente);

        jDesktopPane2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 630, 280));

        jButtonnovo.setBackground(new java.awt.Color(0, 0, 0));
        jButtonnovo.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jButtonnovo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonnovo.setText("Novo");
        jButtonnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnovoActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButtonnovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 640, 80, 30));

        jButtonfinalizar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonfinalizar.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jButtonfinalizar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonfinalizar.setText("Salvar");
        jButtonfinalizar.setEnabled(false);
        jButtonfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfinalizarActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButtonfinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, -1, 30));

        jButtonalterar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonalterar.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jButtonalterar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonalterar.setText("Alterar");
        jButtonalterar.setEnabled(false);
        jButtonalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonalterarActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButtonalterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, 90, 30));

        jButtonexcluir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonexcluir.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jButtonexcluir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonexcluir.setText("Excluir");
        jButtonexcluir.setEnabled(false);
        jButtonexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexcluirActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButtonexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 640, 90, 30));

        jButtonimprimir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonimprimir.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jButtonimprimir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonimprimir.setText("Imprimir");
        jButtonimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonimprimirActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButtonimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 640, 100, 30));

        jLabel12.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fone:");
        jDesktopPane2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 50, -1));

        jCombofone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCombofone.setEnabled(false);
        jCombofone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombofoneActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jCombofone, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 122, 270, 40));

        textobs.setEnabled(false);
        textobs.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jDesktopPane2.add(textobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 260, 60));

        jPanel1.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 920));

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel4))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1378, 815));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxclienteActionPerformed
        // TODO add your handling code here:
        conex.Conexao();
        
         
        conex.Desconecta();
    }//GEN-LAST:event_jComboBoxclienteActionPerformed

    private void jTablePacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacienteMouseClicked
        // TODO add your handling code here:
        String nome_paciente = ""+jTablePaciente.getValueAt(jTablePaciente.getSelectedRow(), 2);
        conex.Conexao();
        conex.executaSql("select *from pacientes where paci_nome_cliente='"+nome_paciente+"'");
        try {
            conex.ResultSet.first();
            jTextcod.setText(String.valueOf(conex.ResultSet.getInt("paci_codigo")));
            jFormattedDATAE.setText(conex.ResultSet.getString("paci_dataemissao"));
            ConexaoBd conexPesquisa = new ConexaoBd();
            conexPesquisa.Conexao();
            conexPesquisa.executaSql("select *from clientes2 where cod_cliente="+conex.ResultSet.getInt("paci_codigo"));
            conexPesquisa.ResultSet.first();
            jComboBoxcliente.setSelectedItem(conexPesquisa.ResultSet.getString("nome_cliente"));
            jCombofone.setSelectedItem(conex.ResultSet.getString("paci_fone"));

            jTextarma.setText(conex.ResultSet.getString("paci_tipodearmaçao"));
            jTextmarca.setText(conex.ResultSet.getString("paci_marca"));
            jTextref.setText(conex.ResultSet.getString("paci_ref"));
            jTextcor.setText(conex.ResultSet.getString("paci_cor"));
            jTextvalor.setText(conex.ResultSet.getString("paci_valor"));
            jTextconta.setText(conex.ResultSet.getString("paci_pconta"));
            jTextresta.setText(conex.ResultSet.getString("paci_resta"));
            textobs.setText(conex.ResultSet.getString("paci_obs"));
            jFormattedprometido.setText(conex.ResultSet.getString("paci_prometidopara"));
            jTextforma.setText(conex.ResultSet.getString("paci_formadepat"));
            jTextodesflonge.setText(conex.ResultSet.getString("paci_odesflonge"));
            jTextodcillonge.setText(conex.ResultSet.getString("paci_odcillonge"));
            jTextodeixolonge.setText(conex.ResultSet.getString("paci_odeixolonge"));
            jTextoeesflonge.setText(conex.ResultSet.getString("paci_oeesflonge"));
            jTextoecillonge.setText(conex.ResultSet.getString("paci_oecillonge"));
            jTextoeeixolonge.setText(conex.ResultSet.getString("paci_oeeixolonge"));
            jTextodesfperto.setText(conex.ResultSet.getString("paci_odesfperto"));
            jTextodcilperto.setText(conex.ResultSet.getString("paci_odcilperto"));
            jTextodeixoperto.setText(conex.ResultSet.getString("paci_odeixoperto"));
            jTextoeesfperto.setText(conex.ResultSet.getString("paci_oeesfperto"));
            jTextoecilperto.setText(conex.ResultSet.getString("paci_oecilperto"));
            jTextoeeixoperto.setText(conex.ResultSet.getString("paci_oeeixoperto"));
            jTextdp.setText(conex.ResultSet.getString("paci_dp"));
            jTextalt.setText(conex.ResultSet.getString("paci_alt"));
            jTexttipodelente.setText(conex.ResultSet.getString("paci_tipodelente"));

            jButtonalterar.setEnabled(true);
            jButtonnovo.setEnabled(true);
            jButtonimprimir.setEnabled(true);
            jButtonexcluir.setEnabled(true);
            jButtonfinalizar.setEnabled(false);

            conexPesquisa.Desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro Ao Selecionar Dados"+ex.getMessage());
    }//GEN-LAST:event_jTablePacienteMouseClicked
    
    
        
} 
   public void PreencherTabela(String Sql){
       
       ArrayList dados = new ArrayList();
          String [] colunas = new String []{"Nº","Data Da Emissao","Cliente","Fone","Tipo De Armaçao","Marca","REF.","Cor","Valor R$","P/Conta R$","Resta R$","OBS", "Prometido Para","Forma de Patº","OD ESF LONGE","OD CIL LONGE","OD EIXO LONGE","OE ESF LONGE","OE CIL LONGE","OE EIXO LONGE","OD ESF PERTO","OD CIL PERTO","OD EIXO PERTO","OE ESF PERTO","OE CIL PERTO","OE EIXO PERTO","DP","ALT","TIPO DE LENTE"};
          conex.Conexao();
          conex.executaSql(Sql);
          
          try {
              conex.ResultSet.first();
              do {
                  
                  dados.add(new Object[] {conex.ResultSet.getInt("paci_codigo"),conex.ResultSet.getString("paci_dataemissao"),conex.ResultSet.getString("nome_cliente"),conex.ResultSet.getString("paci_fone"),conex.ResultSet.getString("paci_tipodearmaçao"),conex.ResultSet.getString("paci_marca"),conex.ResultSet.getString("paci_ref"),conex.ResultSet.getString("paci_cor"),conex.ResultSet.getString("paci_valor"),conex.ResultSet.getString("paci_pconta"),conex.ResultSet.getString("paci_resta"),conex.ResultSet.getString("paci_obs"),conex.ResultSet.getString("paci_prometidopara"),conex.ResultSet.getString("paci_formadepat"),conex.ResultSet.getString("paci_odesflonge"),conex.ResultSet.getString("paci_odcillonge"),conex.ResultSet.getString("paci_odeixolonge"),    conex.ResultSet.getString("paci_oeesflonge"),conex.ResultSet.getString("paci_oecillonge"),conex.ResultSet.getString("paci_oeeixolonge"),   conex.ResultSet.getString("paci_odesfperto"),conex.ResultSet.getString("paci_odcilperto"),conex.ResultSet.getString("paci_odeixoperto"),  conex.ResultSet.getString("paci_oeesfperto"),conex.ResultSet.getString("paci_oecilperto"),conex.ResultSet.getString("paci_oeeixoperto"),conex.ResultSet.getString("paci_dp"),conex.ResultSet.getString("paci_alt"),conex.ResultSet.getString("paci_tipodelente")});
                  
              }while (conex.ResultSet.next());
          }catch (SQLException ex) {
              
          }
          ModeloTab modelo = new ModeloTab(dados, colunas);
          
          jTablePaciente.setModel(modelo);
          jTablePaciente.getColumnModel().getColumn(0).setPreferredWidth(50);
          jTablePaciente.getColumnModel().getColumn(0).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(1).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(1).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(2).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(2).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(3).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(3).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(4).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(4).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(5).setPreferredWidth(80);
          jTablePaciente.getColumnModel().getColumn(5).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(6).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(6).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(7).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(7).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(8).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(8).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(9).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(9).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(10).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(10).setResizable(false); 
          jTablePaciente.getColumnModel().getColumn(11).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(11).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(12).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(12).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(13).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(13).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(14).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(14).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(15).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(15).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(16).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(16).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(17).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(17).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(18).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(18).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(19).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(19).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(20).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(20).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(21).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(21).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(22).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(22).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(23).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(23).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(24).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(24).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(25).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(25).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(26).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(26).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(27).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(27).setResizable(false);
          jTablePaciente.getColumnModel().getColumn(28).setPreferredWidth(100);
          jTablePaciente.getColumnModel().getColumn(28).setResizable(false);
          
          
          
          
          jTablePaciente.getTableHeader().setReorderingAllowed(false);
          jTablePaciente.setAutoResizeMode(jTablePaciente.AUTO_RESIZE_OFF);
          jTablePaciente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
          conex.Desconecta();
       
       
       
   }
   
   
   
        
    private void jButtonfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfinalizarActionPerformed

        if (flag==1){
            pac.setDataemissao(jFormattedDATAE.getText());
            pac.setNome_cliente((String) jComboBoxcliente.getSelectedItem() );
            pac.setFone((String)jCombofone.getSelectedItem());
            pac.setTipoarmaçao(jTextarma.getText());
            pac.setMarca(jTextmarca.getText());
            pac.setRef(jTextref.getText());
            pac.setCor(jTextcor.getText());
            pac.setValor(jTextvalor.getText());
            pac.setPconta(jTextconta.getText());
            pac.setResta(jTextresta.getText());
            pac.setObs(textobs.getText());
            pac.setPrometidopara(jFormattedprometido.getText());
            pac.setFormadepat(jTextforma.getText());
            pac.setOdesflonge(jTextodesflonge.getText());
            pac.setOdcillonge(jTextodcillonge.getText());
            pac.setOdeixolonge(jTextodeixolonge.getText());
            pac.setOeesflonge(jTextoeesflonge.getText());
            pac.setOecillonge(jTextoecillonge.getText());
            pac.setOeeixolonge(jTextoeeixolonge.getText());
            pac.setOdesfperto(jTextodesfperto.getText());
            pac.setOdcilperto(jTextodcilperto.getText());
            pac.setOdeixoperto(jTextodeixoperto.getText());
            pac.setOeesfperto(jTextoeesfperto.getText());
            pac.setOecilperto(jTextoecilperto.getText());
            pac.setOeeixoperto(jTextoeeixoperto.getText());
            pac.setDp(jTextdp.getText());
            pac.setAlt(jTextalt.getText());
            pac.setTipodelente(jTexttipodelente.getText());
            dao.Salvar(pac);

            PreencherTabela("select paci_codigo ,paci_dataemissao,nome_cliente,paci_fone,paci_tipodearmaçao,paci_marca,paci_ref,paci_cor,paci_valor,paci_pconta,paci_resta,paci_obs,paci_prometidopara,paci_formadepat,paci_odesflonge,paci_odcillonge,paci_odeixolonge,paci_oeesflonge,paci_oecillonge,paci_oeeixolonge,paci_odesfperto,paci_odcilperto,paci_odeixoperto,paci_oeesfperto,paci_oecilperto,paci_oeeixoperto,paci_dp,paci_alt,paci_tipodelente from pacientes inner join clientes2 on paci_codigo=cod_cliente order by cod_cliente");

            jButtonfinalizar.setEnabled(!true);
            jTextcod.setEnabled(!true);
            jFormattedDATAE.setEnabled(!true);
            jComboBoxcliente.setEnabled(!true);
            jCombofone.setEnabled(!true);
            jTextarma.setEnabled(!true);
            jTextmarca.setEnabled(!true);
            jTextref.setEnabled(!true);
            jTextcor.setEnabled(!true);
            jTextvalor.setEnabled(!true);
            jTextconta.setEnabled(!true);
            jTextresta.setEnabled(!true);
            textobs.setEnabled(!true);
            jFormattedprometido.setEnabled(!true);
            jTextforma.setEnabled(!true);
            jTextodesflonge.setEnabled(!true);
            jTextodcillonge.setEnabled(!true);
            jTextodcillonge.setEnabled(!true);
            jTextodeixolonge.setEnabled(!true);
            jTextoeesflonge.setEnabled(!true);
            jTextoecillonge.setEnabled(!true);
            jTextoecillonge.setEnabled(!true);
            jTextoeeixolonge.setEnabled(!true);
            jTextodesfperto.setEnabled(!true);
            jTextodcilperto.setEnabled(!true);
            jTextodcilperto.setEnabled(!true);
            jTextodeixoperto.setEnabled(!true);
            jTextoeesfperto.setEnabled(!true);
            jTextoecilperto.setEnabled(!true);
            jTextoecilperto.setEnabled(!true);
            jTextoeeixoperto.setEnabled(!true);
            jTextdp.setEnabled(!true);
            jTextalt.setEnabled(!true);
            jTexttipodelente.setEnabled(!true);

            jButtonfinalizar.setEnabled(!true);
            jButtonnovo.setEnabled(!false);
            jButtonalterar.setEnabled(false);
            jButtonexcluir.setEnabled(!false);

            jTextcod.setText("");
            jFormattedDATAE.setText("");
            jTextarma.setText("");
            jTextmarca.setText("");
            jTextref.setText("");
            jTextcor.setText("");
            jTextvalor.setText("");
            jTextconta.setText("");
            jTextresta.setText("");
            textobs.setText("");
            jFormattedprometido.setText("");
            jTextforma.setText("");
            jTextodesflonge.setText("");
            jTextodcillonge.setText("");
            jTextodcillonge.setText("");
            jTextodeixolonge.setText("");
            jTextoeesflonge.setText("");
            jTextoecillonge.setText("");
            jTextoecillonge.setText("");
            jTextoeeixolonge.setText("");
            jTextodesfperto.setText("");
            jTextodcilperto.setText("");
            jTextodcilperto.setText("");
            jTextodeixoperto.setText("");
            jTextoeesfperto.setText("");
            jTextoecilperto.setText("");
            jTextoecilperto.setText("");
            jTextoeeixoperto.setText("");
            jTextdp.setText("");
            jTextalt.setText("");
            jTexttipodelente.setText("");

        }else{
            pac.setDataemissao(jFormattedDATAE.getText());
            pac.setNome_cliente((String) jComboBoxcliente.getSelectedItem() );
            pac.setFone((String)jCombofone.getSelectedItem());
            pac.setTipoarmaçao(jTextarma.getText());
            pac.setMarca(jTextmarca.getText());
            pac.setRef(jTextref.getText());
            pac.setCor(jTextcor.getText());
            pac.setValor(jTextvalor.getText());
            pac.setPconta(jTextconta.getText());
            pac.setResta(jTextresta.getText());
            pac.setObs(textobs.getText());
            pac.setPrometidopara(jFormattedprometido.getText());
            pac.setFormadepat(jTextforma.getText());
            pac.setOdesflonge(jTextodesflonge.getText());
            pac.setOdcillonge(jTextodcillonge.getText());
            pac.setOdeixolonge(jTextodeixolonge.getText());
            pac.setOeesflonge(jTextoeesflonge.getText());
            pac.setOecillonge(jTextoecillonge.getText());
            pac.setOeeixolonge(jTextoeeixolonge.getText());
            pac.setOdesfperto(jTextodesfperto.getText());
            pac.setOdcilperto(jTextodcilperto.getText());
            pac.setOdeixoperto(jTextodeixoperto.getText());
            pac.setOeesfperto(jTextoeesfperto.getText());
            pac.setOecilperto(jTextoecilperto.getText());
            pac.setOeeixoperto(jTextoeeixoperto.getText());
            pac.setDp(jTextdp.getText());
            pac.setAlt(jTextalt.getText());
            pac.setTipodelente(jTexttipodelente.getText());
            pac.setPaci_codigo(Integer.parseInt(jTextcod.getText()));
            dao.Alterar(pac);

            PreencherTabela("select paci_codigo ,paci_dataemissao,nome_cliente,paci_fone,paci_tipodearmaçao,paci_marca,paci_ref,paci_cor,paci_valor,paci_pconta,paci_resta,paci_obs,paci_prometidopara,paci_formadepat,paci_odesflonge,paci_odcillonge,paci_odeixolonge,paci_oeesflonge,paci_oecillonge,paci_oeeixolonge,paci_odesfperto,paci_odcilperto,paci_odeixoperto,paci_oeesfperto,paci_oecilperto,paci_oeeixoperto,paci_dp,paci_alt,paci_tipodelente from pacientes inner join clientes2 on paci_codigo=cod_cliente order by cod_cliente");

            jButtonfinalizar.setEnabled(!true);
            jTextcod.setEnabled(!true);
            jFormattedDATAE.setEnabled(!true);
            jComboBoxcliente.setEnabled(!true);
            jCombofone.setEnabled(!true);
            jTextarma.setEnabled(!true);
            jTextmarca.setEnabled(!true);
            jTextref.setEnabled(!true);
            jTextcor.setEnabled(!true);
            jTextvalor.setEnabled(!true);
            jTextconta.setEnabled(!true);
            jTextresta.setEnabled(!true);
            textobs.setEnabled(!true);
            jFormattedprometido.setEnabled(!true);
            jTextforma.setEnabled(!true);
            jTextodesflonge.setEnabled(!true);
            jTextodcillonge.setEnabled(!true);
            jTextodcillonge.setEnabled(!true);
            jTextodeixolonge.setEnabled(!true);
            jTextoeesflonge.setEnabled(!true);
            jTextoecillonge.setEnabled(!true);
            jTextoecillonge.setEnabled(!true);
            jTextoeeixolonge.setEnabled(!true);
            jTextodesfperto.setEnabled(!true);
            jTextodcilperto.setEnabled(!true);
            jTextodcilperto.setEnabled(!true);
            jTextodeixoperto.setEnabled(!true);
            jTextoeesfperto.setEnabled(!true);
            jTextoecilperto.setEnabled(!true);
            jTextoecilperto.setEnabled(!true);
            jTextoeeixoperto.setEnabled(!true);
            jTextdp.setEnabled(!true);
            jTextalt.setEnabled(!true);
            jTexttipodelente.setEnabled(!true);

            jButtonfinalizar.setEnabled(!true);
            jButtonnovo.setEnabled(!false);
            jButtonalterar.setEnabled(false);
            jButtonexcluir.setEnabled(!false);

            jTextcod.setText("");
            jFormattedDATAE.setText("");
            jTextarma.setText("");
            jTextmarca.setText("");
            jTextref.setText("");
            jTextcor.setText("");
            jTextvalor.setText("");
            jTextconta.setText("");
            jTextresta.setText("");
            textobs.setText("");
            jFormattedprometido.setText("");
            jTextforma.setText("");
            jTextodesflonge.setText("");
            jTextodcillonge.setText("");
            jTextodcillonge.setText("");
            jTextodeixolonge.setText("");
            jTextoeesflonge.setText("");
            jTextoecillonge.setText("");
            jTextoecillonge.setText("");
            jTextoeeixolonge.setText("");
            jTextodesfperto.setText("");
            jTextodcilperto.setText("");
            jTextodcilperto.setText("");
            jTextodeixoperto.setText("");
            jTextoeesfperto.setText("");
            jTextoecilperto.setText("");
            jTextoecilperto.setText("");
            jTextoeeixoperto.setText("");
            jTextdp.setText("");
            jTextalt.setText("");
            jTexttipodelente.setText("");

        }
    }//GEN-LAST:event_jButtonfinalizarActionPerformed

    private void jButtonalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonalterarActionPerformed
        // TODO add your handling code here:

        flag =2;

        jButtonfinalizar.setEnabled(true);

        jButtonfinalizar.setEnabled(true);
        jTextcod.setEnabled(true);
        jFormattedDATAE.setEnabled(true);
        jComboBoxcliente.setEnabled(true);
        jCombofone.setEnabled(true);
        jTextarma.setEnabled(true);
        jTextmarca.setEnabled(true);
        jTextref.setEnabled(true);
        jTextcor.setEnabled(true);
        jTextvalor.setEnabled(true);
        jTextconta.setEnabled(true);
        jTextresta.setEnabled(true);
        textobs.setEnabled(true);
        jFormattedprometido.setEnabled(true);
        jTextforma.setEnabled(true);
        jTextodesflonge.setEnabled(true);
        jTextodcillonge.setEnabled(true);
        jTextodcillonge.setEnabled(true);
        jTextodeixolonge.setEnabled(true);
        jTextoeesflonge.setEnabled(true);
        jTextoecillonge.setEnabled(true);
        jTextoecillonge.setEnabled(true);
        jTextoeeixolonge.setEnabled(true);
        jTextodesfperto.setEnabled(true);
        jTextodcilperto.setEnabled(true);
        jTextodcilperto.setEnabled(true);
        jTextodeixoperto.setEnabled(true);
        jTextoeesfperto.setEnabled(true);
        jTextoecilperto.setEnabled(true);
        jTextoecilperto.setEnabled(true);
        jTextoeeixoperto.setEnabled(true);
        jTextdp.setEnabled(true);
        jTextalt.setEnabled(true);
        jTexttipodelente.setEnabled(true);

        jButtonfinalizar.setEnabled(true);
        jButtonnovo.setEnabled(false);
        jButtonalterar.setEnabled(false);
        jButtonexcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonalterarActionPerformed

    private void jButtonimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonimprimirActionPerformed
        // TODO add your handling code here:
        ImpressaoPaci Imprime = new ImpressaoPaci();
        List listade_dados = GetDados();
        Imprime.Imprime_Relatorio(listade_dados);
    }//GEN-LAST:event_jButtonimprimirActionPerformed

    private void jButtonexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexcluirActionPerformed
        // TODO add your handling code here:

        resposta=JOptionPane.showConfirmDialog(rootPane,"DESEJA REALMENTE EXCLUIR?");
        if (resposta == JOptionPane.YES_OPTION){
            pac.setPaci_codigo(Integer.parseInt(jTextcod.getText()));
            dao.Excluir(pac);

            PreencherTabela("select paci_codigo ,paci_dataemissao,nome_cliente,paci_fone,paci_tipodearmaçao,paci_marca,paci_ref,paci_cor,paci_valor,paci_pconta,paci_resta,paci_obs,paci_prometidopara,paci_formadepat,paci_odesflonge,paci_odcillonge,paci_odeixolonge,paci_oeesflonge,paci_oecillonge,paci_oeeixolonge,paci_odesfperto,paci_odcilperto,paci_odeixoperto,paci_oeesfperto,paci_oecilperto,paci_oeeixoperto,paci_dp,paci_alt,paci_tipodelente from pacientes inner join clientes2 on paci_codigo=cod_cliente order by cod_cliente");

            jTextcod.setText("");
            jFormattedDATAE.setText("");
            jTextarma.setText("");
            jTextmarca.setText("");
            jTextref.setText("");
            jTextcor.setText("");
            jTextvalor.setText("");
            jTextconta.setText("");
            jTextresta.setText("");
            textobs.setText("");
            jFormattedprometido.setText("");
            jTextforma.setText("");
            jTextodesflonge.setText("");
            jTextodcillonge.setText("");
            jTextodcillonge.setText("");
            jTextodeixolonge.setText("");
            jTextoeesflonge.setText("");
            jTextoecillonge.setText("");
            jTextoecillonge.setText("");
            jTextoeeixolonge.setText("");
            jTextodesfperto.setText("");
            jTextodcilperto.setText("");
            jTextodcilperto.setText("");
            jTextodeixoperto.setText("");
            jTextoeesfperto.setText("");
            jTextoecilperto.setText("");
            jTextoecilperto.setText("");
            jTextoeeixoperto.setText("");
            jTextdp.setText("");
            jTextalt.setText("");
            jTexttipodelente.setText("");

            jButtonfinalizar.setEnabled(!true);
            jTextcod.setEnabled(!true);
            jFormattedDATAE.setEnabled(!true);
            jComboBoxcliente.setEnabled(!true);
            jCombofone.setEnabled(!true);
            jTextarma.setEnabled(!true);
            jTextmarca.setEnabled(!true);
            jTextref.setEnabled(!true);
            jTextcor.setEnabled(!true);
            jTextvalor.setEnabled(!true);
            jTextconta.setEnabled(!true);
            jTextresta.setEnabled(!true);
            textobs.setEnabled(!true);
            jFormattedprometido.setEnabled(!true);
            jTextforma.setEnabled(!true);
            jTextodesflonge.setEnabled(!true);
            jTextodcillonge.setEnabled(!true);
            jTextodcillonge.setEnabled(!true);
            jTextodeixolonge.setEnabled(!true);
            jTextoeesflonge.setEnabled(!true);
            jTextoecillonge.setEnabled(!true);
            jTextoecillonge.setEnabled(!true);
            jTextoeeixolonge.setEnabled(!true);
            jTextodesfperto.setEnabled(!true);
            jTextodcilperto.setEnabled(!true);
            jTextodcilperto.setEnabled(!true);
            jTextodeixoperto.setEnabled(!true);
            jTextoeesfperto.setEnabled(!true);
            jTextoecilperto.setEnabled(!true);
            jTextoecilperto.setEnabled(!true);
            jTextoeeixoperto.setEnabled(!true);
            jTextdp.setEnabled(!true);
            jTextalt.setEnabled(!true);
            jTexttipodelente.setEnabled(!true);

            jButtonfinalizar.setEnabled(true);
            jButtonnovo.setEnabled(true);
            jButtonalterar.setEnabled(!false);
            jButtonexcluir.setEnabled(!false);

        }
    }//GEN-LAST:event_jButtonexcluirActionPerformed

    private void jButtonnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnovoActionPerformed
        // TODO add your handling code here:

        flag=1;
        jButtonfinalizar.setEnabled(true);
        jTextcod.setEnabled(true);
        jFormattedDATAE.setEnabled(true);
        jComboBoxcliente.setEnabled(true);
        jCombofone.setEnabled(true);
        jTextarma.setEnabled(true);
        jTextmarca.setEnabled(true);
        jTextref.setEnabled(true);
        jTextcor.setEnabled(true);
        jTextvalor.setEnabled(true);
        jTextconta.setEnabled(true);
        jTextresta.setEnabled(true);
        textobs.setEnabled(true);
        jFormattedprometido.setEnabled(true);
        jTextforma.setEnabled(true);
        jTextodesflonge.setEnabled(true);
        jTextodcillonge.setEnabled(true);
        jTextodcillonge.setEnabled(true);
        jTextodeixolonge.setEnabled(true);
        jTextoeesflonge.setEnabled(true);
        jTextoecillonge.setEnabled(true);
        jTextoecillonge.setEnabled(true);
        jTextoeeixolonge.setEnabled(true);
        jTextodesfperto.setEnabled(true);
        jTextodcilperto.setEnabled(true);
        jTextodcilperto.setEnabled(true);
        jTextodeixoperto.setEnabled(true);
        jTextoeesfperto.setEnabled(true);
        jTextoecilperto.setEnabled(true);
        jTextoecilperto.setEnabled(true);
        jTextoeeixoperto.setEnabled(true);
        jTextdp.setEnabled(true);
        jTextalt.setEnabled(true);
        jTexttipodelente.setEnabled(true);

        jTextcod.setText("");
        jFormattedDATAE.setText("");
        jTextarma.setText("");
        jTextmarca.setText("");
        jTextref.setText("");
        jTextcor.setText("");
        jTextvalor.setText("");
        jTextconta.setText("");
        jTextresta.setText("");
        textobs.setText("");
        jFormattedprometido.setText("");
        jTextforma.setText("");
        jTextodesflonge.setText("");
        jTextodcillonge.setText("");
        jTextodcillonge.setText("");
        jTextodeixolonge.setText("");
        jTextoeesflonge.setText("");
        jTextoecillonge.setText("");
        jTextoecillonge.setText("");
        jTextoeeixolonge.setText("");
        jTextodesfperto.setText("");
        jTextodcilperto.setText("");
        jTextodcilperto.setText("");
        jTextodeixoperto.setText("");
        jTextoeesfperto.setText("");
        jTextoecilperto.setText("");
        jTextoecilperto.setText("");
        jTextoeeixoperto.setText("");
        jTextdp.setText("");
        jTextalt.setText("");
        jTexttipodelente.setText("");

        jButtonfinalizar.setEnabled(true);
        jButtonnovo.setEnabled(false);
        jButtonalterar.setEnabled(true);
        jButtonexcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonnovoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: buscar

        jButtonfinalizar.setEnabled(!true);
        jTextcod.setEnabled(!true);
        jFormattedDATAE.setEnabled(!true);
        jComboBoxcliente.setEnabled(!true);
        jCombofone.setEnabled(!true);
        jTextarma.setEnabled(!true);
        jTextmarca.setEnabled(!true);
        jTextref.setEnabled(!true);
        jTextcor.setEnabled(!true);
        jTextvalor.setEnabled(!true);
        jTextconta.setEnabled(!true);
        jTextresta.setEnabled(!true);
        textobs.setEnabled(!true);
        jFormattedprometido.setEnabled(!true);
        jTextforma.setEnabled(!true);
        jTextodesflonge.setEnabled(!true);
        jTextodcillonge.setEnabled(!true);
        jTextodcillonge.setEnabled(!true);
        jTextodeixolonge.setEnabled(!true);
        jTextoeesflonge.setEnabled(!true);
        jTextoecillonge.setEnabled(!true);
        jTextoecillonge.setEnabled(!true);
        jTextoeeixolonge.setEnabled(!true);
        jTextodesfperto.setEnabled(!true);
        jTextodcilperto.setEnabled(!true);
        jTextodcilperto.setEnabled(!true);
        jTextodeixoperto.setEnabled(!true);
        jTextoeesfperto.setEnabled(!true);
        jTextoecilperto.setEnabled(!true);
        jTextoecilperto.setEnabled(!true);
        jTextoeeixoperto.setEnabled(!true);
        jTextdp.setEnabled(!true);
        jTextalt.setEnabled(!true);
        jTexttipodelente.setEnabled(!true);

        jButtonfinalizar.setEnabled(true);
        jButtonnovo.setEnabled(false);
        jButtonalterar.setEnabled(!false);
        jButtonexcluir.setEnabled(!false);

        pac.setPesquisa(jTextbuscar.getText());
        BenasPacientes pac1 = dao.BuscaPaciente(pac);
        jTextcod.setText(String.valueOf(pac1.getPaci_codigo()));
        jFormattedDATAE.setText(pac1.getDataemissao());
        jComboBoxcliente.setSelectedItem(pac1.getNome_cliente());
        jCombofone.setSelectedItem(pac1.getFone());
        jTextarma.setText(pac1.getTipoarmaçao());
        jTextmarca.setText(pac1.getMarca());
        jTextref.setText(pac1.getRef());
        jTextcor.setText(pac1.getCor());
        jTextvalor.setText(pac1.getValor());
        jTextconta.setText(pac1.getPconta());
        jTextresta.setText(pac1.getResta());
        textobs.setText(pac1.getObs());
        jFormattedprometido.setText(pac1.getPrometidopara());
        jTextforma.setText(pac1.getFormadepat());
        jTextodesflonge.setText(pac1.getOdesflonge());
        jTextodcillonge.setText(pac1.getOdeixolonge());
        jTextodeixolonge.setText(pac1.getOdeixolonge());
        jTextoeesflonge.setText(pac1.getOeesflonge());
        jTextoecillonge.setText(pac1.getOeeixolonge());
        jTextoeeixolonge.setText(pac1.getOeeixolonge());
        jTextodesfperto.setText(pac1.getOdesfperto());
        jTextodcilperto.setText(pac1.getOdeixoperto());
        jTextodeixoperto.setText(pac1.getOdeixoperto());
        jTextoeesfperto.setText(pac1.getOeesfperto());
        jTextoecilperto.setText(pac1.getOeeixoperto());
        jTextoeeixoperto.setText(pac1.getOeeixoperto());
        jTextdp.setText(pac1.getDp());
        jTextalt.setText(pac1.getAlt());
        jTexttipodelente.setText(pac1.getTipodelente());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCombofoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombofoneActionPerformed
        // TODO add your handling code here:
        conex.Conexao();
        conex.Desconecta();
    }//GEN-LAST:event_jCombofoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laboratorio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laboratorio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laboratorio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laboratorio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laboratorio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonalterar;
    private javax.swing.JButton jButtonexcluir;
    private javax.swing.JButton jButtonfinalizar;
    private javax.swing.JButton jButtonimprimir;
    private javax.swing.JButton jButtonnovo;
    private javax.swing.JComboBox<String> jComboBoxcliente;
    private javax.swing.JComboBox<String> jCombofone;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JFormattedTextField jFormattedDATAE;
    private javax.swing.JFormattedTextField jFormattedprometido;
    private javax.swing.JLabel jLabeLESF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelALT;
    private javax.swing.JLabel jLabelCIL;
    private javax.swing.JLabel jLabelDP;
    private javax.swing.JLabel jLabelEIXO;
    private javax.swing.JLabel jLabelLONGE;
    private javax.swing.JLabel jLabelOD;
    private javax.swing.JLabel jLabelOD2;
    private javax.swing.JLabel jLabelOE;
    private javax.swing.JLabel jLabelOE2;
    private javax.swing.JLabel jLabelPERTO;
    private javax.swing.JLabel jLabelTIPOLENTE;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSeparator jSeparatorBORDAS;
    private javax.swing.JTable jTablePaciente;
    private javax.swing.JTextField jTextalt;
    private javax.swing.JTextField jTextarma;
    private javax.swing.JTextField jTextbuscar;
    private javax.swing.JTextField jTextcod;
    private javax.swing.JTextField jTextconta;
    private javax.swing.JTextField jTextcor;
    private javax.swing.JTextField jTextdp;
    private javax.swing.JTextField jTextforma;
    private javax.swing.JTextField jTextmarca;
    private javax.swing.JTextField jTextodcillonge;
    private javax.swing.JTextField jTextodcilperto;
    private javax.swing.JTextField jTextodeixolonge;
    private javax.swing.JTextField jTextodeixoperto;
    private javax.swing.JTextField jTextodesflonge;
    private javax.swing.JTextField jTextodesfperto;
    private javax.swing.JTextField jTextoecillonge;
    private javax.swing.JTextField jTextoecilperto;
    private javax.swing.JTextField jTextoeeixolonge;
    private javax.swing.JTextField jTextoeeixoperto;
    private javax.swing.JTextField jTextoeesflonge;
    private javax.swing.JTextField jTextoeesfperto;
    private javax.swing.JTextField jTextref;
    private javax.swing.JTextField jTextresta;
    private javax.swing.JTextField jTexttipodelente;
    private javax.swing.JTextField jTextvalor;
    private java.awt.TextArea textobs;
    // End of variables declaration//GEN-END:variables


public void preencherPaciente(){
        conex.Conexao();
        conex.executaSql("select *from clientes2 order by  nome_cliente,fone_cliente");
        
        try {
            conex.ResultSet.first();
            jComboBoxcliente.removeAllItems();
            jCombofone.removeAllItems();
            do {
                jComboBoxcliente.addItem(conex.ResultSet.getString("nome_cliente"));
                jCombofone.addItem(conex.ResultSet.getString("fone_cliente"));
                
            }while(conex.ResultSet.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "ERRO"+ex);
        }
        
        conex.Desconecta();
    }
    
 public List GetDados(){
        List lista = new ArrayList();
        AuxiPaciente print1 = new AuxiPaciente();
        print1.setCodigo(Integer.parseInt(jTextcod.getText()));
        print1.setDataemissao(jFormattedDATAE.getText());
        print1.setPaci_nome_cliente(jComboBoxcliente.getSelectedItem().toString());
        print1.setPaci_fone(jCombofone.getSelectedItem().toString());
        print1.setTipodearmaçao(jTextarma.getText());
        print1.setMarca(jTextmarca.getText());
        print1.setRef(jTextref.getText());
        print1.setCor(jTextcor.getText());
        print1.setValor(jTextvalor.getText());
        print1.setPconta(jTextconta.getText());
        print1.setResta(jTextresta.getText());
        print1.setObs(textobs.getText());
        print1.setPrometidopara(jFormattedprometido.getText());
        print1.setFormadepat(jTextforma.getText());
        print1.setOdesflonge(jTextodesflonge.getText());
        print1.setOdcillonge(jTextodcillonge.getText());
        print1.setOdeixolonge(jTextodeixolonge.getText()); 
        print1.setOeesflonge(jTextoeesflonge.getText());
        print1.setOecillonge(jTextoecillonge.getText());
        print1.setOeeixolonge(jTextoeeixolonge.getText());
        print1.setOdesfperto(jTextodesfperto.getText());
        print1.setOdcilperto(jTextodcilperto.getText());
        print1.setOdeixoperto(jTextodeixoperto.getText());
        print1.setOeesfperto(jTextoeesfperto.getText());
        print1.setOecilperto(jTextoecilperto.getText());
        print1.setOeeixoperto(jTextoeeixoperto.getText());
        print1.setDp(jTextdp.getText());
        print1.setAlt(jTextalt.getText());
        print1.setTipodelente(jTexttipodelente.getText());
        
        
        
        lista.add(print1);
        
        
        return lista; 
    }




    }

